FROM ubuntu:20.04
# Copy Jav deb 파일
COPY . /root/java

ARG version=jdk-11.0.10_linux-x64_bin.deb


RUN apt update && \
    apt install -y libasound2 && \
    apt install nano

 # install java
RUN sh /root/java/install-java.sh $version
