FROM myhahadoop
## Hadoop
# zookeeper server id
RUN echo "3" > /var/lib/zookeeper/myid

## Spark
# install spark
COPY *.tgz spark-3.4.3-bin-hadoop3-scala2.13.tgz
RUN tar xvf spark-3.4.3-bin-hadoop3-scala2.13.tgz && rm *.tgz
RUN ln -s spark-3.4.3-bin-hadoop3-scala2.13 spark

# set configurations, ENV variables
ENV SPARK_HOME=/root/spark
ENV PATH=$PATH:$SPARK_HOME/bin
ENV LD_LIBRARY_PATH=$HADOOP_HOME/lib/native
COPY spark-defaults.conf $SPARK_HOME/conf/spark-defaults.conf
RUN mkdir $SPARK_HOME/logs
WORKDIR $SPARK_HOME

# COPY jar 파일
COPY webtoon-data.csv /root/spark/data/webtoon-data.csv


